name: Restrict Subdirectory Merge
on: push

jobs:
  restrict-subdirectory-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          ACTOR_CONTEXT: ${{ toJson(github.actor) }}
        run: |
          if [ "$ACTOR_CONTEXT" != "SolomonRFeldman" ]; then
            echo "YOU ARE BANNED FROM THIS PLACE, BEGONE!"
            echo "Expected actor: SolomonRFeldman not $ACTOR_CONTEXT"
            exit 1
          else
            echo "Welcome, my guy!"
          fi
